dist: trusty
sudo: false

language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm run build

deploy:
  provider: script
  script: bin/deploy
  on:
    branch: master
