language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4.2

branches:
  only:
  - master

script:
  - npm run build
  - npm run deploy

env:
  global:
    - NODE_ENV=production
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
